import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Import Inter from Google Fonts
import "./globals.css";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";

// Use next/font to import Inter font
const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "400", "600", "900"], // Define the required weights
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-gray-100`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
